def test_this_func():
    print('This is running and expecting a raise Exception')
    # raise Exception('haha this fails')

var = 5
for i in range(var):
    print i





test_this_func()
